export enum CategorieJeu {
    STRATEGIE = 'STRATEGIE',
  AMBIANCE = 'AMBIANCE',
  ENFANT = 'ENFANT',
  FAMILIAL = 'FAMILIAL',
  EXPERT = 'EXPERT',
  AVENTURE = 'AVENTURE',
  HISTORIQUE = 'HISTORIQUE',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  FANTASY = 'FANTASY'
}
