pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        -u root
                        --network projetJeux
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            stages {
                stage('Installation dependances') {
                    steps {
                        dir('projet_groupe4_angular') {
                            sh 'npm install'
                        }
                    }
                }

                                stage('Analyse Sonar') {
                                    steps {
                                        dir('projet_groupe4_angular') {
                                            // Injection sécurisée du token SonarQube depuis Jenkins Credentials
                                            withCredentials([string(credentialsId: 'SONAR_AUTH_TOKEN', variable: 'SONAR_TOKEN')]) {
                                                withSonarQubeEnv('SonarQube') {
                                                    sh """
                                                        ./node_modules/.bin/sonar-scanner -Dsonar.projectKey=projetJeux-angular -Dsonar.projectName=projetJeux-angular -Dsonar.host.url=http://sonarqube:8081 -Dsonar.login=${SONAR_TOKEN}
                                                    """
                                                }
                                            }
                                        }
                                    }
                                }

                stage('Build Angular') {
                    steps {
                        dir('projet_groupe4_angular') {
                            sh './node_modules/.bin/ng build'
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('projet-groupe4-angular') {
                    sh 'docker build -t ajc/projetjeux:angular .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                
                sh 'docker compose up -d --no-deps --build angular'
                
            }
        }
    }
}
