pipeline {
    agent any

    stages {
	stage('Clean MySQL volume') {
            steps {
                script {
                    // Supprime le volume si il existe
                    sh '''
                    if docker volume inspect projetJeux-db-data >/dev/null 2>&1; then
                        echo "Removing existing MySQL volume..."
                        docker volume rm projetJeux-db-data
                    else
                        echo "No existing MySQL volume found."
                    fi
                    '''
                }
            }
        }
	
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network projetJeux
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('projet_groupe4') {

                    
                        // Attente que MySQL soit disponible
            sh '''
            echo "Waiting for MySQL to be ready..."
            until nc -z -v -w30 jeux-mysql 3306
            do
              echo "Waiting for MySQL..."
              sleep 2
            done
            echo "MySQL is up!"
            '''

                        // Lancer Maven + SonarQube
                        withSonarQubeEnv('SonarQube') {
                            sh "mvn clean verify sonar:sonar -Dsonar.projectKey=projetJeux-boot -Dsonar.projectName='projetJeux-boot'"
                        }
                    }
                }
            
        }
	

        stage('Docker Build') {
            steps {
                dir('projet_groupe4') {
                    sh 'docker build -t ajc/projetjeux:boot .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                
                sh 'docker compose up -d --build'
                
            }
        }
    }
}
