pipeline {
    agent any

    stages {
	stage('Check MySQL') {
    steps {
        script {
            // Teste la connexion MySQL sur le réseau Docker
            sh '''
            for i in {1..30}; do
              if docker exec jeux-mysql mysqladmin ping -uroot -proot --silent; then
                echo "MySQL is up!"
                break
              fi
              echo "Waiting for MySQL..."
              sleep 2
            done
            '''
        }
    }
}
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network projetJeux
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('projet_groupe4') {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=projetJeux-boot -Dsonar.projectName='projetJeux-boot'"
                    }
                }
            }
        }
	

        stage('Docker Build') {
            steps {
                dir('projet_groupe4') {
                    sh 'docker build -t ajc/projetjeux:boot .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                
                sh 'docker compose up -d --build'
                
            }
        }
    }
}
